// Generated by CoughSyrup 0.1.0
(function() {
  define(function() {
    var contravenes, descr, each_hyphen_contravenes, each_hyphen_satisfies, each_hyphen_throws, not_hyphen_to_hyphen_throw, satisfies, t, test_hyphen_spec, throws, to_hyphen_be, to_hyphen_be_hyphen_array, to_hyphen_be_hyphen_false, to_hyphen_be_hyphen_fn, to_hyphen_be_hyphen_nbr, to_hyphen_be_hyphen_string, to_hyphen_be_hyphen_true, to_hyphen_equal, to_hyphen_have_hyphen_length, to_hyphen_throw, xdescr, xt;
    descr = function(a1) {
      return function(a2) {
        return describe(a1, a2);
      };
    };
    xdescr = function(a1) {
      return function(a2) {
        return xdescribe(a1, a2);
      };
    };
    t = function(a1) {
      return function(a2) {
        return it(a1, a2);
      };
    };
    xt = function(a1) {
      return function(a2) {
        return xit(a1, a2);
      };
    };
    test_hyphen_spec = function(spec) {
      return function(message) {
        return function(element) {
          return it(message, (function() {
            return spec(element);
          }));
        };
      };
    };
    to_hyphen_throw = function(fn) {
      return function(arg) {
        return expect(fn.bind(null, arg)).toThrow();
      };
    };
    not_hyphen_to_hyphen_throw = function(fn) {
      return function(arg) {
        return expect(fn.bind(null, arg)).not.toThrow();
      };
    };
    to_hyphen_be = function(actual) {
      return function(expected) {
        return expect(expected).toBe(actual);
      };
    };
    to_hyphen_equal = function(actual) {
      return function(expected) {
        return expect(expected).toEqual(actual);
      };
    };
    to_hyphen_be_hyphen_true = function(expected) {
      return expect(expected).toEqual(true);
    };
    to_hyphen_be_hyphen_false = function(expected) {
      return expect(expected).toEqual(false);
    };
    satisfies = function(predicate) {
      return function(input) {
        return expect(predicate(input)).toEqual(true);
      };
    };
    contravenes = function(predicate) {
      return function(input) {
        return expect(predicate(input)).toEqual(false);
      };
    };
    throws = function(predicate) {
      return function(input) {
        return to_hyphen_throw(predicate)(input);
      };
    };
    each_hyphen_satisfies = function(predicate) {
      return function(inputs) {
        return inputs.forEach(satisfies(predicate));
      };
    };
    each_hyphen_contravenes = function(predicate) {
      return function(inputs) {
        return inputs.forEach(contravenes(predicate));
      };
    };
    each_hyphen_throws = function(fn) {
      return function(inputs) {
        return inputs.forEach(to_hyphen_throw(fn));
      };
    };
    to_hyphen_be_hyphen_fn = function(expected) {
      return expect(expected).toEqual(jasmine.any(Function));
    };
    to_hyphen_be_hyphen_array = function(val) {
      return to_hyphen_equal(jasmine.any(Array))(val);
    };
    to_hyphen_be_hyphen_string = function(val) {
      return to_hyphen_equal(jasmine.any(String))(val);
    };
    to_hyphen_be_hyphen_nbr = function(val) {
      return to_hyphen_equal(jasmine.any(Number))(val);
    };
    to_hyphen_have_hyphen_length = function(length) {
      return function(val) {
        return to_hyphen_equal(length)(val.length);
      };
    };
    return {
      contravenes: contravenes,
      descr: descr,
      each_hyphen_contravenes: each_hyphen_contravenes,
      each_hyphen_satisfies: each_hyphen_satisfies,
      each_hyphen_throws: each_hyphen_throws,
      not_hyphen_to_hyphen_throw: not_hyphen_to_hyphen_throw,
      satisfies: satisfies,
      t: t,
      test_hyphen_spec: test_hyphen_spec,
      throws: throws,
      to_hyphen_throw: to_hyphen_throw,
      to_hyphen_be: to_hyphen_be,
      to_hyphen_equal: to_hyphen_equal,
      to_hyphen_be_hyphen_array: to_hyphen_be_hyphen_array,
      to_hyphen_be_hyphen_nbr: to_hyphen_be_hyphen_nbr,
      to_hyphen_be_hyphen_string: to_hyphen_be_hyphen_string,
      to_hyphen_be_hyphen_true: to_hyphen_be_hyphen_true,
      to_hyphen_be_hyphen_false: to_hyphen_be_hyphen_false,
      to_hyphen_be_hyphen_fn: to_hyphen_be_hyphen_fn,
      to_hyphen_have_hyphen_length: to_hyphen_have_hyphen_length,
      xdescr: xdescr,
      xt: xt
    };
  });

}).call(this);
