// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'jFns', 'constants', 'constructors', 'extractors', 'specConstants', 'utilities'], function(_, j, c, g, x, sc, u) {
    var contravenes, descr, each_hyphen_contravenes, each_hyphen_fn_hyphen_result_hyphen_equals, each_hyphen_satisfies, each_hyphen_throws, gen_hyphen_pred_hyphen_guards, satisfies, t, test_hyphen_predicate, test_hyphen_spec, test_hyphen_throwing_hyphen_transformation, test_hyphen_transformation, throws, to_hyphen_be, to_hyphen_be_hyphen_array, to_hyphen_be_hyphen_false, to_hyphen_be_hyphen_fn, to_hyphen_be_hyphen_nbr, to_hyphen_be_hyphen_true, to_hyphen_equal, to_hyphen_have_hyphen_length, to_hyphen_throw, xdescr, xt;
    descr = j.descr, xdescr = j.xdescr, t = j.t, xt = j.xt, test_hyphen_spec = j.test_hyphen_spec, to_hyphen_throw = j.to_hyphen_throw, to_hyphen_be = j.to_hyphen_be, to_hyphen_equal = j.to_hyphen_equal, to_hyphen_be_hyphen_true = j.to_hyphen_be_hyphen_true, to_hyphen_be_hyphen_false = j.to_hyphen_be_hyphen_false, satisfies = j.satisfies, contravenes = j.contravenes, throws = j.throws, each_hyphen_fn_hyphen_result_hyphen_equals = j.each_hyphen_fn_hyphen_result_hyphen_equals, each_hyphen_satisfies = j.each_hyphen_satisfies, each_hyphen_contravenes = j.each_hyphen_contravenes, each_hyphen_throws = j.each_hyphen_throws, to_hyphen_be_hyphen_array = j.to_hyphen_be_hyphen_array, to_hyphen_be_hyphen_fn = j.to_hyphen_be_hyphen_fn, to_hyphen_be_hyphen_nbr = j.to_hyphen_be_hyphen_nbr, to_hyphen_be_hyphen_array = j.to_hyphen_be_hyphen_array, to_hyphen_have_hyphen_length = j.to_hyphen_have_hyphen_length, test_hyphen_predicate = j.test_hyphen_predicate, test_hyphen_transformation = j.test_hyphen_transformation, test_hyphen_throwing_hyphen_transformation = j.test_hyphen_throwing_hyphen_transformation, gen_hyphen_pred_hyphen_guards = j.gen_hyphen_pred_hyphen_guards;
    return descr('test utilities.cough')(function() {
      var bd, initial_hyphen_board, pos1, pos3;
      bd = sc.boards[0];
      pos1 = sc.positions[0];
      pos3 = sc.positions[2];
      initial_hyphen_board = sc.initial_hyphen_board;
      t('test u.available?')(function() {
        var fn, local_hyphen_bds, local_hyphen_src, local_hyphen_tgt;
        local_hyphen_bds = ['r---------------------------------------------------------------', 'rR--------------------------------------------------------------', 'rr--------------------------------------------------------------', 'R---------------------------------------------------------------', 'Rr--------------------------------------------------------------', 'RR--------------------------------------------------------------'];
        local_hyphen_src = g.generate_hyphen_position(0, 0);
        local_hyphen_tgt = g.generate_hyphen_position(0, 1);
        fn = function(board) {
          return u.available_question_(board, local_hyphen_src)(local_hyphen_tgt);
        };
        each_hyphen_satisfies(fn)([local_hyphen_bds[0], local_hyphen_bds[1], local_hyphen_bds[3], local_hyphen_bds[4]]);
        each_hyphen_contravenes(fn)([local_hyphen_bds[2], local_hyphen_bds[5]]);
        return throws(fn)(pos1);
      });
      t('test u.black?')(function() {
        var fn;
        fn = u.black_question_;
        satisfies(fn)(c.black);
        each_hyphen_contravenes(fn)([c.white, c.absent_hyphen_color]);
        return throws(fn)([bd]);
      });
      return t('test u.empty-at?')(function() {
        var fn;
        fn = u.empty_hyphen_at_question_(initial_hyphen_board);
        satisfies(fn)(pos3);
        contravenes(fn)(pos1);
        return throws(fn)(bd);
      });
    });
  });

}).call(this);
