// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'types'], function(_, y) {
    var generate_hyphen_plural_hyphen_validator, generate_hyphen_singular_hyphen_validator, plural_hyphen_validators, singular_hyphen_validators, validation_hyphen_pairs, vow_hyphen_all_hyphen_colors, vow_hyphen_all_hyphen_indices, vow_hyphen_all_hyphen_pairs, vow_hyphen_all_hyphen_passant_hyphen_positions, vow_hyphen_all_hyphen_position_hyphen_components, vow_hyphen_all_hyphen_positions, vow_hyphen_board, vow_hyphen_bounded, vow_hyphen_castling_hyphen_right, vow_hyphen_castling_hyphen_right_hyphen_set, vow_hyphen_chart, vow_hyphen_chart2, vow_hyphen_chessman, vow_hyphen_chessman_hyphen_type, vow_hyphen_color, vow_hyphen_color_hyphen_pair, vow_hyphen_context, vow_hyphen_index, vow_hyphen_integral_hyphen_pair, vow_hyphen_map, vow_hyphen_pair, vow_hyphen_passant_hyphen_position, vow_hyphen_path, vow_hyphen_pawn_hyphen_direction, vow_hyphen_player, vow_hyphen_position, vow_hyphen_position_hyphen_component, vow_hyphen_query, vow_hyphen_rook, vow_hyphen_setting, vow_hyphen_square, _ref, _ref1;
    validation_hyphen_pairs = [[y.board_question_, 'board'], [y.bounded_question_, 'bounded number'], [y.castling_hyphen_right_question_, 'castling right'], [y.castling_hyphen_right_hyphen_set_question_, 'castling right set'], [y.chart_question_, 'chart'], [y.chart2_question_, 'chart2'], [y.chessman_question_, 'chessman'], [y.chessman_hyphen_type_question_, 'chessman type'], [y.color_question_, 'color'], [y.color_hyphen_pair_question_, 'color pair'], [y.context_question_, 'context'], [y.index_question_, 'index'], [y.integral_hyphen_pair_question_, 'integral pair'], [y.map_question_, 'map'], [y.pair_question_, 'pair'], [y.passant_hyphen_position_question_, 'passant position'], [y.path_question_, 'path'], [y.pawn_hyphen_direction_question_, 'pawn direction'], [y.player_question_, 'player'], [y.position_question_, 'position'], [y.position_hyphen_component_question_, 'position component'], [y.query_question_, 'query'], [y.rook_question_, 'rook'], [y.setting_question_, 'setting'], [y.square_question_, 'square']];
    generate_hyphen_singular_hyphen_validator = function(_arg) {
      var pred, str;
      pred = _arg[0], str = _arg[1];
      return _.vowWith(pred)("Invalid " + str);
    };
    singular_hyphen_validators = (_ref = _.map(generate_hyphen_singular_hyphen_validator)(validation_hyphen_pairs), vow_hyphen_board = _ref[0], vow_hyphen_bounded = _ref[1], vow_hyphen_castling_hyphen_right = _ref[2], vow_hyphen_castling_hyphen_right_hyphen_set = _ref[3], vow_hyphen_chart = _ref[4], vow_hyphen_chart2 = _ref[5], vow_hyphen_chessman = _ref[6], vow_hyphen_chessman_hyphen_type = _ref[7], vow_hyphen_color = _ref[8], vow_hyphen_color_hyphen_pair = _ref[9], vow_hyphen_context = _ref[10], vow_hyphen_index = _ref[11], vow_hyphen_integral_hyphen_pair = _ref[12], vow_hyphen_map = _ref[13], vow_hyphen_pair = _ref[14], vow_hyphen_passant_hyphen_position = _ref[15], vow_hyphen_path = _ref[16], vow_hyphen_pawn_hyphen_direction = _ref[17], vow_hyphen_player = _ref[18], vow_hyphen_position = _ref[19], vow_hyphen_position_hyphen_component = _ref[20], vow_hyphen_query = _ref[21], vow_hyphen_rook = _ref[22], vow_hyphen_setting = _ref[23], vow_hyphen_square = _ref[24], _ref);
    generate_hyphen_plural_hyphen_validator = function(validator) {
      return _.map(validator);
    };
    plural_hyphen_validators = (_ref1 = _.map(generate_hyphen_plural_hyphen_validator)([vow_hyphen_color, vow_hyphen_index, vow_hyphen_pair, vow_hyphen_passant_hyphen_position, vow_hyphen_position, vow_hyphen_position_hyphen_component]), vow_hyphen_all_hyphen_colors = _ref1[0], vow_hyphen_all_hyphen_indices = _ref1[1], vow_hyphen_all_hyphen_pairs = _ref1[2], vow_hyphen_all_hyphen_passant_hyphen_positions = _ref1[3], vow_hyphen_all_hyphen_positions = _ref1[4], vow_hyphen_all_hyphen_position_hyphen_components = _ref1[5], _ref1);
    return {
      vow_hyphen_all_hyphen_colors: vow_hyphen_all_hyphen_colors,
      vow_hyphen_all_hyphen_indices: vow_hyphen_all_hyphen_indices,
      vow_hyphen_all_hyphen_pairs: vow_hyphen_all_hyphen_pairs,
      vow_hyphen_all_hyphen_passant_hyphen_positions: vow_hyphen_all_hyphen_passant_hyphen_positions,
      vow_hyphen_all_hyphen_position_hyphen_components: vow_hyphen_all_hyphen_position_hyphen_components,
      vow_hyphen_all_hyphen_positions: vow_hyphen_all_hyphen_positions,
      vow_hyphen_board: vow_hyphen_board,
      vow_hyphen_bounded: vow_hyphen_bounded,
      vow_hyphen_castling_hyphen_right: vow_hyphen_castling_hyphen_right,
      vow_hyphen_castling_hyphen_right_hyphen_set: vow_hyphen_castling_hyphen_right_hyphen_set,
      vow_hyphen_chart: vow_hyphen_chart,
      vow_hyphen_chart2: vow_hyphen_chart2,
      vow_hyphen_chessman: vow_hyphen_chessman,
      vow_hyphen_chessman_hyphen_type: vow_hyphen_chessman_hyphen_type,
      vow_hyphen_color: vow_hyphen_color,
      vow_hyphen_color_hyphen_pair: vow_hyphen_color_hyphen_pair,
      vow_hyphen_context: vow_hyphen_context,
      vow_hyphen_index: vow_hyphen_index,
      vow_hyphen_integral_hyphen_pair: vow_hyphen_integral_hyphen_pair,
      vow_hyphen_map: vow_hyphen_map,
      vow_hyphen_pair: vow_hyphen_pair,
      vow_hyphen_passant_hyphen_position: vow_hyphen_passant_hyphen_position,
      vow_hyphen_path: vow_hyphen_path,
      vow_hyphen_pawn_hyphen_direction: vow_hyphen_pawn_hyphen_direction,
      vow_hyphen_player: vow_hyphen_player,
      vow_hyphen_position: vow_hyphen_position,
      vow_hyphen_query: vow_hyphen_query,
      vow_hyphen_rook: vow_hyphen_rook,
      vow_hyphen_setting: vow_hyphen_setting,
      vow_hyphen_square: vow_hyphen_square
    };
  });

}).call(this);
