// Generated by CoughSyrup 0.1.0
(function() {
  define(['constants'], function(c) {
    var black_question_, defaults, to_hyphen_black, to_hyphen_white, white_question_;
    black_question_ = function(sq) {
      return sq === String.toLowerCase(sq) && sq !== c.empty_hyphen_square;
    };
    defaults = function(mixin) {
      return function(val) {
        var prop;
        for (prop in mixin) {
          if (val[prop] === void 0) {
            val[prop] = mixin[prop];
          }
        }
        return val;
      };
    };
    white_question_ = function(sq) {
      return sq === String.toUpperCase(sq) && sq !== c.empty_hyphen_square;
    };
    to_hyphen_black = String.toLowerCase;
    to_hyphen_white = String.toUpperCase;
    return {
      black_question_: black_question_,
      defaults: defaults,
      white_question_: white_question_,
      to_hyphen_black: to_hyphen_black,
      to_hyphen_white: to_hyphen_white
    };
  });

}).call(this);
