// Generated by CoughSyrup 0.1.0
(function() {
  define(['constants', 'extractors', 'utilities', 'assertions'], function(c, x, u, v) {
    var basicMove, modifyCastlingRights;
    basicMove = function(bd, src) {
      return function(tgt) {
        var bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece, src_hyphen_chessman;
        v.vow_hyphen_board(bd);
        v.vow_hyphen_all_hyphen_positions([src, tgt]);
        src_hyphen_chessman = x.square_hyphen_at(bd)(src);
        bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece = u.replace(src_hyphen_chessman, bd, tgt);
        return u.replace(c.empty_hyphen_square, bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece, src);
      };
    };
    modifyCastlingRights = function(rts) {
      v.vow_hyphen_castling_hyphen_right_hyphen_set(rts);
      return rts;
    };
    return {
      basicMove: basicMove,
      modifyCastlingRights: modifyCastlingRights
    };
  });

}).call(this);
