// Generated by CoughSyrup 0.1.0
(function() {
  define(function() {
    var absent_hyphen_color, bishop, black, black_hyphen_bishop, black_hyphen_chessmen, black_hyphen_king, black_hyphen_knight, black_hyphen_pawn, black_hyphen_player, black_hyphen_queen, black_hyphen_rook, castling_hyphen_black, castling_hyphen_black_hyphen_kingward, castling_hyphen_black_hyphen_queenward, castling_hyphen_white, castling_hyphen_white_hyphen_kingward, castling_hyphen_white_hyphen_queenward, chessman_hyphen_colors, chessman_hyphen_types, chessmen, colors, king, knight, pawn, piece_hyphen_types, players, queen, rook, white, white_hyphen_bishop, white_hyphen_chessmen, white_hyphen_king, white_hyphen_knight, white_hyphen_pawn, white_hyphen_player, white_hyphen_queen, white_hyphen_rook, _ref;
    black_hyphen_chessmen = [black_hyphen_king = 'k', black_hyphen_queen = 'q', black_hyphen_rook = 'r', black_hyphen_bishop = 'b', black_hyphen_knight = 'n', black_hyphen_pawn = 'p'];
    white_hyphen_chessmen = [white_hyphen_king = 'K', white_hyphen_queen = 'Q', white_hyphen_rook = 'R', white_hyphen_bishop = 'B', white_hyphen_knight = 'N', white_hyphen_pawn = 'P'];
    chessmen = black_hyphen_chessmen.concat(white_hyphen_chessmen);
    absent_hyphen_color = '-';
    chessman_hyphen_colors = (_ref = ['w', 'b'], white = _ref[0], black = _ref[1], _ref);
    colors = [absent_hyphen_color].concat(chessman_hyphen_colors);
    piece_hyphen_types = [king = 'king', queen = 'queen', rook = 'rook', bishop = 'bishop', knight = 'knight'];
    chessman_hyphen_types = piece_hyphen_types.concat([pawn = 'pawn']);
    castling_hyphen_black = [castling_hyphen_black_hyphen_kingward = 'k', castling_hyphen_black_hyphen_queenward = 'q'];
    castling_hyphen_white = [castling_hyphen_white_hyphen_kingward = 'K', castling_hyphen_white_hyphen_queenward = 'Q'];
    players = [white_hyphen_player = 'w', black_hyphen_player = 'b'];
    return {
      absent_hyphen_color: absent_hyphen_color,
      bishop: bishop,
      black: black,
      black_hyphen_bishop: black_hyphen_bishop,
      black_hyphen_chessmen: black_hyphen_chessmen,
      black_hyphen_king: black_hyphen_king,
      black_hyphen_knight: black_hyphen_knight,
      black_hyphen_pawn: black_hyphen_pawn,
      black_hyphen_player: black_hyphen_player,
      black_hyphen_queen: black_hyphen_queen,
      black_hyphen_rook: black_hyphen_rook,
      castling_hyphen_black: castling_hyphen_black,
      castling_hyphen_black_hyphen_kingward: castling_hyphen_black_hyphen_kingward,
      castling_hyphen_black_hyphen_queenward: castling_hyphen_black_hyphen_queenward,
      castling_hyphen_white: castling_hyphen_white,
      castling_hyphen_white_hyphen_kingward: castling_hyphen_white_hyphen_kingward,
      castling_hyphen_white_hyphen_queenward: castling_hyphen_white_hyphen_queenward,
      chessman_hyphen_colors: chessman_hyphen_colors,
      chessman_hyphen_types: chessman_hyphen_types,
      chessmen: chessmen,
      colors: colors,
      empty_hyphen_square: '-',
      full_hyphen_castling_hyphen_rts: 'KQkq',
      king: king,
      knight: knight,
      move_hyphen_offsets: {
        king: [[1, 1], [1, 0], [1, -1], [0, 1], [0, -1], [-1, 1], [-1, 0], [-1, -1]],
        queen: [[1, 1], [1, 0], [1, -1], [0, 1], [0, -1], [-1, 1], [-1, 0], [-1, -1]],
        rook: [[1, 0], [0, 1], [0, -1], [-1, 0]],
        bishop: [[1, 1], [1, -1], [-1, 1], [-1, -1]],
        knight: [[1, 2], [1, -2], [-1, 2], [-1, -2], [2, 1], [2, -1], [-2, 1], [-2, -1]]
      },
      nbr_hyphen_chessmen_hyphen_per_hyphen_color: 16,
      no_hyphen_castling_hyphen_rts: '-',
      no_hyphen_pawn_hyphen_promotion: '-',
      pawn: pawn,
      pawn_hyphen_home_hyphen_ranks: {
        black: 1,
        white: 6
      },
      piece_hyphen_home_hyphen_ranks: {
        black: 0,
        white: 7
      },
      piece_hyphen_types: piece_hyphen_types,
      players: players,
      queen: queen,
      rook: rook,
      unset_hyphen_check_hyphen_status: {},
      unset_hyphen_passant_hyphen_pos: '-',
      unset_hyphen_promotion_hyphen_pos: false,
      white: white,
      white_hyphen_bishop: white_hyphen_bishop,
      white_hyphen_chessmen: white_hyphen_chessmen,
      white_hyphen_king: white_hyphen_king,
      white_hyphen_knight: white_hyphen_knight,
      white_hyphen_pawn: white_hyphen_pawn,
      white_hyphen_player: white_hyphen_player,
      white_hyphen_queen: white_hyphen_queen,
      white_hyphen_rook: white_hyphen_rook
    };
  });

}).call(this);
