// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'constants', 'types', 'assertions'], function(_, c, y, v) {
    var board_hyphen_from, castling_hyphen_rights_hyphen_from, chessman_hyphen_type_hyphen_at, chessman_hyphen_type_hyphen_of, chessmen_hyphen_from, color_hyphen_at, color_hyphen_of, corresponding_hyphen_black_hyphen_chessman, file_hyphen_of, get_hyphen_ctx, get_hyphen_promotion_hyphen_msg, map_hyphen_from, passant_hyphen_from, path_hyphen_from, rank_hyphen__ampersand__hyphen_file_hyphen_from, rank_hyphen_of, split_hyphen__ampersand__hyphen_indexify, square_hyphen_at, src_hyphen_chessman_hyphen_from, src_hyphen_from, src_hyphen_setting_hyphen_from, tgt_hyphen_from, tgt_hyphen_setting_hyphen_from, to_hyphen_1d, type_hyphen_from;
    split_hyphen__ampersand__hyphen_indexify = function(i) {
      return function(str) {
        var array, indexify;
        array = _.split('')(str);
        indexify = function(component) {
          i += 1;
          return [component, i];
        };
        return _.map(indexify)(array);
      };
    };
    to_hyphen_1d = function(_arg) {
      var file, rank;
      rank = _arg[0], file = _arg[1];
      v.vow_hyphen_position([rank, file]);
      return 8 * rank + file;
    };
    corresponding_hyphen_black_hyphen_chessman = function(chessman) {
      v.vow_hyphen_chessman(chessman);
      if (_.isUC(chessman)) {
        return _.toLC(chessman);
      } else {
        return chessman;
      }
    };
    board_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.setting_question_, y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var board, pos;
          board = _arg[0], pos = _arg[1];
          return board;
        }, function(_arg) {
          var board, path;
          board = _arg[0], path = _arg[1];
          return board;
        }, function(_arg) {
          var board, path, _ref;
          (_ref = _arg[0], board = _ref.board), path = _arg[1];
          return board;
        }
      ];
      return _["switch"]([y.setting_question_, y.map_question_, y.chart_question_])(evaluators)(val);
    };
    castling_hyphen_rights_hyphen_from = function(chart) {
      v.vow_hyphen_chart(chart);
      return chary.castlingRights;
    };
    chessman_hyphen_type_hyphen_at = function(setting) {
      v.vow_hyphen_setting(setting);
      return chessman_hyphen_type_hyphen_of(square_hyphen_at(setting));
    };
    chessman_hyphen_type_hyphen_of = function(chessman) {
      var abbrev, type_hyphen_of;
      v.vow_hyphen_chessman(chessman);
      abbrev = corresponding_hyphen_black_hyphen_chessman(chessman);
      type_hyphen_of = _.zipAssign(c.black_hyphen_chessmen)(c.chessman_hyphen_types);
      return type_hyphen_of[abbrev];
    };
    color_hyphen_at = function(setting) {
      v.vow_hyphen_setting(setting);
      return color_hyphen_of(square_hyphen_at(setting));
    };
    color_hyphen_of = function(square) {
      v.vow_hyphen_square(square);
      return _.switchWith(c.absent_hyphen_color)([_.isLC, _.isUC])([c.black, c.white])(square);
    };
    file_hyphen_of = function(_arg) {
      var file, rank;
      rank = _arg[0], file = _arg[1];
      v.vow_hyphen_position([rank, file]);
      return file;
    };
    get_hyphen_promotion_hyphen_msg = function(response) {
      return response.promotion_hyphen_pos;
    };
    get_hyphen_ctx = function(response) {
      return response.ctx;
    };
    map_hyphen_from = function(chart) {
      var board, path, _ref;
      v.vow_hyphen_chart(chart);
      (_ref = chart[0], board = _ref.board), path = chart[1];
      return [board, path];
    };
    chessmen_hyphen_from = function(board, color) {
      var chessmen_hyphen_of_hyphen_specified_hyphen_color, color_hyphen_predicate, squares;
      squares = split_hyphen__ampersand__hyphen_indexify(-1)(board);
      color_hyphen_predicate = function(_arg) {
        var idx, sq;
        sq = _arg[0], idx = _arg[1];
        return of_hyphen_color_question_(color)(sq);
      };
      return chessmen_hyphen_of_hyphen_specified_hyphen_color = _.filter(color_hyphen_predicate)(squares);
    };
    path_hyphen_from = function(pair) {
      return pair[1];
    };
    passant_hyphen_from = function(chart) {
      var passantPosition;
      v.vow_hyphen_chart(chart);
      passantPosition = chart[0].passantPosition;
      return passantPosition;
    };
    rank_hyphen__ampersand__hyphen_file_hyphen_from = function(_arg) {
      var file, rank;
      rank = _arg[0], file = _arg[1];
      _.vowStruct([y.path_question_, y.integral_hyphen_pair_question_])([rank, file]);
      return [rank, file];
    };
    rank_hyphen_of = function(_arg) {
      var file, rank;
      rank = _arg[0], file = _arg[1];
      v.vow_hyphen_position([rank, file]);
      return rank;
    };
    square_hyphen_at = function(_arg) {
      var board, pos;
      board = _arg[0], pos = _arg[1];
      v.vow_hyphen_setting([board, pos]);
      return _.charAt(to_hyphen_1d(pos))(board);
    };
    src_hyphen_chessman_hyphen_from = function(val) {
      return square_hyphen_at(src_hyphen_setting_hyphen_from(val));
    };
    src_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.path_question_, y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var src, tgt;
          tgt = _arg[0], src = _arg[1];
          return src;
        }, function(_arg) {
          var board, src, tgt, _ref;
          board = _arg[0], (_ref = _arg[1], tgt = _ref[0], src = _ref[1]);
          return src;
        }, function(_arg) {
          var board, src, tgt, _ref, _ref1;
          (_ref = _arg[0], board = _ref.board), (_ref1 = _arg[1], tgt = _ref1[0], src = _ref1[1]);
          return src;
        }
      ];
      return _["switch"]([y.path_question_, y.map_question_, y.chart_question_])(evaluators)(val);
    };
    src_hyphen_setting_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var board, src, tgt, _ref;
          board = _arg[0], (_ref = _arg[1], tgt = _ref[0], src = _ref[1]);
          return [board, src];
        }, function(_arg) {
          var board, src, tgt, _ref, _ref1;
          (_ref = _arg[0], board = _ref.board), (_ref1 = _arg[1], tgt = _ref1[0], src = _ref1[1]);
          return [board, src];
        }
      ];
      return _["switch"]([y.map_question_, y.chart_question_])(evaluators)(val);
    };
    tgt_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.path_question_, y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var src, tgt;
          tgt = _arg[0], src = _arg[1];
          return tgt;
        }, function(_arg) {
          var board, src, tgt, _ref;
          board = _arg[0], (_ref = _arg[1], tgt = _ref[0], src = _ref[1]);
          return tgt;
        }, function(_arg) {
          var board, src, tgt, _ref, _ref1;
          (_ref = _arg[0], board = _ref.board), (_ref1 = _arg[1], tgt = _ref1[0], src = _ref1[1]);
          return tgt;
        }
      ];
      return _["switch"]([y.path_question_, y.map_question_, y.chart_question_])(evaluators)(val);
    };
    tgt_hyphen_setting_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var board, src, tgt, _ref;
          board = _arg[0], (_ref = _arg[1], tgt = _ref[0], src = _ref[1]);
          return [board, tgt];
        }, function(_arg) {
          var board, src, tgt, _ref, _ref1;
          (_ref = _arg[0], board = _ref.board), (_ref1 = _arg[1], tgt = _ref1[0], src = _ref1[1]);
          return [board, tgt];
        }
      ];
      return _["switch"]([y.map_question_, y.chart_question_])(evaluators)(val);
    };
    type_hyphen_from = function(val) {
      var evaluators;
      _.vowStruct([y.setting_question_, y.map_question_, y.chart_question_])(val);
      evaluators = [
        function(_arg) {
          var board, pos;
          board = _arg[0], pos = _arg[1];
          return chessman_hyphen_type_hyphen_at([board, pos]);
        }, function(_arg) {
          var board, src, tgt, _ref;
          board = _arg[0], (_ref = _arg[1], tgt = _ref[0], src = _ref[1]);
          return chessman_hyphen_type_hyphen_at([board, src]);
        }, function(_arg) {
          var board, src, tgt, _ref, _ref1;
          (_ref = _arg[0], board = _ref.board), (_ref1 = _arg[1], tgt = _ref1[0], src = _ref1[1]);
          return chessman_hyphen_type_hyphen_at([board, src]);
        }
      ];
      return _["switch"]([y.setting_question_, y.map_question_, y.chart_question_])(evaluators)(val);
    };
    return {
      board_hyphen_from: board_hyphen_from,
      castling_hyphen_rights_hyphen_from: castling_hyphen_rights_hyphen_from,
      chessman_hyphen_type_hyphen_at: chessman_hyphen_type_hyphen_at,
      chessman_hyphen_type_hyphen_of: chessman_hyphen_type_hyphen_of,
      corresponding_hyphen_black_hyphen_chessman: corresponding_hyphen_black_hyphen_chessman,
      color_hyphen_at: color_hyphen_at,
      color_hyphen_of: color_hyphen_of,
      file_hyphen_of: file_hyphen_of,
      get_hyphen_promotion_hyphen_msg: get_hyphen_promotion_hyphen_msg,
      get_hyphen_ctx: get_hyphen_ctx,
      map_hyphen_from: map_hyphen_from,
      chessmen_hyphen_from: chessmen_hyphen_from,
      path_hyphen_from: path_hyphen_from,
      passant_hyphen_from: passant_hyphen_from,
      rank_hyphen__ampersand__hyphen_file_hyphen_from: rank_hyphen__ampersand__hyphen_file_hyphen_from,
      rank_hyphen_of: rank_hyphen_of,
      split_hyphen__ampersand__hyphen_indexify: split_hyphen__ampersand__hyphen_indexify,
      square_hyphen_at: square_hyphen_at,
      src_hyphen_chessman_hyphen_from: src_hyphen_chessman_hyphen_from,
      src_hyphen_from: src_hyphen_from,
      src_hyphen_setting_hyphen_from: src_hyphen_setting_hyphen_from,
      tgt_hyphen_from: tgt_hyphen_from,
      tgt_hyphen_setting_hyphen_from: tgt_hyphen_setting_hyphen_from,
      to_hyphen_1d: to_hyphen_1d,
      type_hyphen_from: type_hyphen_from
    };
  });

}).call(this);
