// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'slider', 'king', 'assertions'], function(_, slider_hyphen_fns, king_hyphen_fns, v) {
    var access_hyphen_dispatch_hyphen_table, call, dispatch_hyphen_table, test_hyphen_mode;
    dispatch_hyphen_table = {
      king: king_hyphen_fns,
      queen: slider_hyphen_fns,
      bishop: slider_hyphen_fns
    };
    call = access_hyphen_dispatch_hyphen_table = function(fn_hyphen_name) {
      return function(chessman_hyphen_type) {
        _.vowStr(fn_hyphen_name);
        v.vow_hyphen_chessman_hyphen_type(chessman_hyphen_type);
        return dispatch_hyphen_table[chessman_hyphen_type][fn_hyphen_name];
      };
    };
    test_hyphen_mode = {
      call: call
    };
    return test_hyphen_mode;
  });

}).call(this);
