// Generated by CoughSyrup 0.1.0
(function() {
  define(['base-helpers', 'constants', 'constructors', 'extractors', 'utilities', 'stepper', 'assertions'], function(_, c, g, x, u, stepper_hyphen_fns, v) {
    var K, KQ, NO, Q, c1, c1_hyphen_key, c8, c8_hyphen_key, castle, castling_hyphen_permitted_question_, castling_hyphen_tgts, castling_question_, g1, g1_hyphen_key, g8, g8_hyphen_key, gen_hyphen_pos, getPotentialKingAttacks, getPotentialMoves, get_hyphen_potential_hyphen_castling_hyphen_moves, k, king_hyphen_castling_hyphen_tgt_hyphen_files, king_hyphen_castling_hyphen_tgts, kq, modifyCastlingRights, new_hyphen_castling_hyphen_rts, no_hyphen_rts, pf, possible_hyphen_rook_hyphen_paths, public_hyphen_fns, q, rook_hyphen_castling_hyphen_path, rook_hyphen_castling_hyphen_srcs, rook_hyphen_castling_hyphen_tgts, t0, t1, t12, t2, t3, t34, t4, _ref;
    KQ = 'KQ';
    kq = 'kq';
    K = 'K';
    Q = 'Q';
    k = 'k';
    q = 'q';
    NO = '-';
    gen_hyphen_pos = g.generate_hyphen_position;
    no_hyphen_rts = c.no_hyphen_castling_hyphen_rts;
    king_hyphen_castling_hyphen_tgt_hyphen_files = [2, 6];
    king_hyphen_castling_hyphen_tgts = [c1 = gen_hyphen_pos(7, 2), g1 = gen_hyphen_pos(7, 6), c8 = gen_hyphen_pos(0, 2), g8 = gen_hyphen_pos(0, 6)];
    _ref = king_hyphen_castling_hyphen_tgts.map(JSON.stringify), c1_hyphen_key = _ref[0], g1_hyphen_key = _ref[1], c8_hyphen_key = _ref[2], g8_hyphen_key = _ref[3];
    possible_hyphen_rook_hyphen_paths = [[5, 7], [3, 0], [61, 63], [59, 56]];
    rook_hyphen_castling_hyphen_srcs = {};
    rook_hyphen_castling_hyphen_srcs[c8_hyphen_key] = gen_hyphen_pos(0, 0);
    rook_hyphen_castling_hyphen_srcs[g8_hyphen_key] = gen_hyphen_pos(0, 7);
    rook_hyphen_castling_hyphen_srcs[c1_hyphen_key] = gen_hyphen_pos(7, 0);
    rook_hyphen_castling_hyphen_srcs[g1_hyphen_key] = gen_hyphen_pos(7, 7);
    rook_hyphen_castling_hyphen_tgts = {};
    rook_hyphen_castling_hyphen_tgts[c8_hyphen_key] = gen_hyphen_pos(0, 3);
    rook_hyphen_castling_hyphen_tgts[g8_hyphen_key] = gen_hyphen_pos(0, 5);
    rook_hyphen_castling_hyphen_tgts[c1_hyphen_key] = gen_hyphen_pos(7, 3);
    rook_hyphen_castling_hyphen_tgts[g1_hyphen_key] = gen_hyphen_pos(7, 5);
    t0 = [];
    t1 = [c1];
    t2 = [g1];
    t12 = [c1, g1];
    t3 = [c8];
    t4 = [g8];
    t34 = [c8, g8];
    new_hyphen_castling_hyphen_rts = {};
    new_hyphen_castling_hyphen_rts[c.white] = {
      KQkq: kq,
      KQk: k,
      KQq: q,
      KQ: NO,
      Kkq: kq,
      Kk: k,
      Kq: q,
      K: NO,
      Qkq: kq,
      Qk: k,
      Qq: q,
      Q: NO,
      kq: kq,
      k: k,
      q: q,
      '-': NO
    };
    new_hyphen_castling_hyphen_rts[c.black] = {
      KQkq: KQ,
      Qkq: Q,
      Kkq: K,
      kq: NO,
      KQq: KQ,
      Qq: Q,
      Kq: K,
      q: NO,
      KQk: KQ,
      Qk: Q,
      Kk: K,
      k: NO,
      KQ: KQ,
      Q: Q,
      K: K,
      '-': NO
    };
    castling_hyphen_tgts = {};
    castling_hyphen_tgts[c.white] = {
      KQkq: t12,
      KQk: t12,
      KQq: t12,
      KQ: t12,
      Qkq: t1,
      Qk: t1,
      Qq: t1,
      Q: t1,
      Kkq: t2,
      Kk: t2,
      Kq: t2,
      K: t2,
      kq: t0,
      k: t0,
      q: t0,
      '-': t0
    };
    castling_hyphen_tgts[c.black] = {
      KQkq: t34,
      Qkq: t34,
      Kkq: t34,
      kq: t34,
      KQq: t3,
      Qq: t3,
      Kq: t3,
      q: t3,
      KQk: t4,
      Qk: t4,
      Kk: t4,
      k: t4,
      KQ: t0,
      Q: t0,
      K: t0,
      '-': t0
    };
    castling_question_ = function(src, tgt) {
      return Math.abs(u.file_hyphen_difference(src, tgt)) > 1;
    };
    castling_hyphen_permitted_question_ = function(castling_hyphen_rts, black_question_) {
      return function(rank_hyphen_diff) {
        var kingward_question_, matcher;
        kingward_question_ = rank_hyphen_diff > 0;
        matcher = u.castling_hyphen_matcher(black_question_, kingward_question_);
        return /#{matcher}/.test(castling_hyphen_rts);
      };
    };
    get_hyphen_potential_hyphen_castling_hyphen_moves = function(color, castling_hyphen_rts) {
      return castling_hyphen_tgts[color][castling_hyphen_rts];
    };
    getPotentialKingAttacks = function(bd, src) {
      v.vow_hyphen_board(bd);
      v.vow_hyphen_position(src);
      return getPotentialMoves(bd, src, no_hyphen_rts);
    };
    getPotentialMoves = function(bd, src, rts) {
      var basic_hyphen_moves, king_hyphen_color;
      v.vow_hyphen_board(bd);
      v.vow_hyphen_position(src);
      v.vow_hyphen_castling_hyphen_right_hyphen_set(rts);
      king_hyphen_color = x.color_hyphen_at(bd)(src);
      basic_hyphen_moves = pf.getBasicPotentialMoves(bd, src, void 0, void 0, c.king);
      if (rts === no_hyphen_rts) {
        return basic_hyphen_moves;
      }
      return basic_hyphen_moves.concat(get_hyphen_potential_hyphen_castling_hyphen_moves(king_hyphen_color, rts));
    };
    modifyCastlingRights = function(rts, src) {
      var king_hyphen_color;
      v.vow_hyphen_castling_hyphen_right_hyphen_set(rts);
      v.vow_hyphen_position(src);
      king_hyphen_color = x.rank_hyphen_of(src) === 0 ? c.black : c.white;
      return new_hyphen_castling_hyphen_rts[king_hyphen_color][rts];
    };
    rook_hyphen_castling_hyphen_path = function(king_hyphen_tgt) {
      var key, src, tgt;
      key = JSON.stringify(king_hyphen_tgt);
      src = rook_hyphen_castling_hyphen_srcs[key];
      tgt = rook_hyphen_castling_hyphen_tgts[key];
      return [src, tgt];
    };
    pf = public_hyphen_fns = _.defaults({
      getPotentialKingAttacks: getPotentialKingAttacks,
      getPotentialMoves: getPotentialMoves,
      modifyCastlingRights: modifyCastlingRights
    }, stepper_hyphen_fns);
    castle = (function(simple_hyphen_move) {
      return function(bd, src, tgt) {
        var bd_hyphen_after_hyphen_king_hyphen_moves, rook_hyphen_src, rook_hyphen_tgt, _ref1;
        _ref1 = rook_hyphen_castling_hyphen_path(tgt), rook_hyphen_src = _ref1[0], rook_hyphen_tgt = _ref1[1];
        bd_hyphen_after_hyphen_king_hyphen_moves = simple_hyphen_move(bd, src)(tgt);
        return simple_hyphen_move(bd_hyphen_after_hyphen_king_hyphen_moves, rook_hyphen_src)(rook_hyphen_tgt);
      };
    })(pf.move);
    pf.move = (function(non_hyphen_castling_hyphen_move) {
      return function(bd, src) {
        return function(tgt) {
          v.vow_hyphen_board(bd);
          v.vow_hyphen_all_hyphen_positions([src, tgt]);
          if (castling_question_(src, tgt)) {
            return castle(bd, src, tgt);
          } else {
            return non_hyphen_castling_hyphen_move(bd, src)(tgt);
          }
        };
      };
    })(pf.move);
    return public_hyphen_fns;
  });

}).call(this);
