// Generated by CoughSyrup 0.1.0
(function() {
  define(['base-helpers', 'constants', 'constructors', 'extractors', 'utilities', 'stepper', 'assertions'], function(_, c, g, x, u, stepper_hyphen_fns, v) {
    var get_hyphen_potential_hyphen_moves, pf, public_hyphen_fns;
    pf = public_hyphen_fns = _.defaults({}, stepper_hyphen_fns);
    get_hyphen_potential_hyphen_moves = function(bd, src) {
      v.vow_hyphen_board(bd);
      v.vow_hyphen_position(src);
      return pf.getBasicPotentialMoves(bd, src, void 0, void 0, c.knight);
    };
    pf.getPotentialKingAttacks = get_hyphen_potential_hyphen_moves;
    pf.getPotentialMoves = get_hyphen_potential_hyphen_moves;
    pf.move = pf.basicMove;
    return public_hyphen_fns;
  });

}).call(this);
