// Generated by CoughSyrup 0.1.0
(function() {
  define(['base-helpers', 'constants', 'constructors', 'extractors', 'utilities', 'stepper', 'assertions'], function(_, c, g, x, u, stepper_hyphen_fns, v) {
    var pf, public_hyphen_fns;
    pf = public_hyphen_fns = _.defaults(stepper_hyphen_fns)({});
    pf.getPotentialKingAttacks = (function(getPotentialMoves) {
      return function(bd, src) {
        v.vow_hyphen_board(bd);
        v.vow_hyphen_position(src);
        return getPotentialMoves(bd, src, void 0, void 0, c.knight);
      };
    })(pf.getPotentialMoves);
    pf.getPotentialMoves = pf.getPotentialKingAttacks;
    return public_hyphen_fns;
  });

}).call(this);
