// Generated by CoughSyrup 0.1.0
(function() {
  define(['base-helpers', 'constants', 'constructors', 'extractors', 'utilities', 'stepper', 'assertions'], function(_, c, g, x, u, stepper_hyphen_fns, v) {
    var getPotentialKingAttacks, getPotentialMoves, pf, public_hyphen_fns;
    getPotentialKingAttacks = function(bd, src) {
      v.vow_hyphen_board(bd);
      v.vow_hyphen_position(src);
      return pf.getBasicPotentialMoves(bd, src, void 0, void 0, c.knight);
    };
    getPotentialMoves = getPotentialKingAttacks;
    pf = public_hyphen_fns = _.defaults(stepper_hyphen_fns)({
      getPotentialKingAttacks: getPotentialKingAttacks,
      getPotentialMoves: getPotentialMoves
    });
    return public_hyphen_fns;
  });

}).call(this);
