// Generated by CoughSyrup 0.1.0
(function() {
  require.config({
    shim: {
      jqueryUi: {
        deps: ['jquery'],
        exports: 'jqueryUi'
      }
    },
    paths: {
      jquery: 'http://code.jquery.com/jquery-1.9.1',
      jqueryUi: 'http://code.jquery.com/ui/1.10.3/jquery-ui',
      react: 'http://fb.me/react-0.10.0'
    }
  });

  require(['constants', 'game-ui'], function(c, game) {
    return game.render(c.initial_hyphen_context);
  });

}).call(this);
