// Generated by CoughSyrup 0.1.0
(function() {
  require.config({
    shim: {
      jqueryUi: {
        deps: ['jquery'],
        exports: 'jqueryUi'
      }
    },
    paths: {
      jquery: 'http://code.jquery.com/jquery-1.9.1',
      jqueryUi: 'http://code.jquery.com/ui/1.10.3/jquery-ui',
      react: 'http://fb.me/react-0.10.0'
    }
  });

  require(['constants', 'game-ui'], function(c, game) {
    var initial_hyphen_board, initial_hyphen_ctx;
    initial_hyphen_board = 'rnbqkbnrPppppppp--------------------------------PpPPPPPPRNBQKBNR';
    initial_hyphen_ctx = {
      board: initial_hyphen_board,
      player: c.white,
      castlingRights: c.full_hyphen_castling_hyphen_rts,
      passantPosition: c.unset_hyphen_passant_hyphen_pos,
      promotionPosition: c.unset_hyphen_promotion_hyphen_pos
    };
    return game.render(initial_hyphen_ctx);
  });

}).call(this);
