// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'constants', 'constructors', 'utilities', 'extractors', 'chessman', 'assertions'], function(_, c, g, u, x, chessman_hyphen_fns, v) {
    var basicMove, modifyCastlingRights, public_hyphen_fns, setPassantPosition, setPassantPosition2, setPromotionPosition, setPromotionPosition2;
    basicMove = function(chart2) {
      return function(tgt) {
        var bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece, board, src, src_hyphen_chessman;
        v.vow_hyphen_chart2(chart2);
        v.vow_hyphen_position(tgt);
        board = x.board_hyphen_from(chart2);
        src = x.position_hyphen_from(chart2);
        src_hyphen_chessman = x.square_hyphen_at(board)(src);
        bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece = u.replace(src_hyphen_chessman, board, tgt);
        return u.replace(c.empty_hyphen_square, bd_hyphen_w_slash__hyphen_duplicate_hyphen_piece, src);
      };
    };
    modifyCastlingRights = function(chart2) {
      v.vow_hyphen_chart2(chart2);
      return x.castling_hyphen_rights_hyphen_from(chart2);
    };
    setPromotionPosition = function(chart2) {
      v.vow_hyphen_chart2(chart2);
      return c.unset_hyphen_promotion_hyphen_pos;
    };
    setPromotionPosition2 = function() {
      return c.unset_hyphen_promotion_hyphen_pos;
    };
    setPassantPosition = function(chart2) {
      v.vow_hyphen_chart2(chart2);
      return c.unset_hyphen_passant_hyphen_pos;
    };
    setPassantPosition2 = function() {
      return c.unset_hyphen_passant_hyphen_pos;
    };
    public_hyphen_fns = _.defaults([chessman_hyphen_fns])({
      basicMove: basicMove,
      modifyCastlingRights: modifyCastlingRights,
      setPassantPosition: setPassantPosition,
      setPromotionPosition: setPromotionPosition,
      setPassantPosition2: setPassantPosition2,
      setPromotionPosition2: setPromotionPosition2
    });
    return public_hyphen_fns;
  });

}).call(this);
