// Generated by CoughSyrup 0.1.0
(function() {
  define(['base-helpers', 'constants', 'chessman'], function(_, c, chessman_hyphen_fns) {
    var public_hyphen_fns, setPassantPosition, setPromotionPosition;
    setPassantPosition = function() {
      return c.unset_hyphen_passant_hyphen_pos;
    };
    setPromotionPosition = function() {
      return c.unset_hyphen_promotion_hyphen_pos;
    };
    public_hyphen_fns = _.defaults({
      setPassantPosition: setPassantPosition,
      setPromotionPosition: setPromotionPosition
    }, chessman_hyphen_fns);
    return public_hyphen_fns;
  });

}).call(this);
