// Generated by CoughSyrup 0.1.0
(function() {
  define(['mydash', 'extractors', 'utilities', 'constructors', 'types', 'piece', 'assertions'], function(_, x, u, g, y, piece_hyphen_fns, v) {
    var getBasicPotentialMoves, getBasicPotentialMoves2, get_hyphen_basic_hyphen_potential_hyphen_moves, position_question_, public_hyphen_fns;
    position_question_ = y.position_question_;
    get_hyphen_basic_hyphen_potential_hyphen_moves = function(rank, file, offsets, available_question_) {
      var dir, file_hyphen_diff, new_hyphen_file, new_hyphen_rank, potential_hyphen_moves, rank_hyphen_diff, tgt, _i, _len, _ref, _ref1;
      v.vow_hyphen_all_hyphen_position_hyphen_components([rank, file]);
      _.vowAllAry(offsets);
      _.vowFn(available_question_);
      potential_hyphen_moves = [];
      for (_i = 0, _len = offsets.length; _i < _len; _i++) {
        dir = offsets[_i];
        _ref = x.rank_hyphen__ampersand__hyphen_file_hyphen_from(dir), rank_hyphen_diff = _ref[0], file_hyphen_diff = _ref[1];
        _ref1 = [rank + rank_hyphen_diff, file + file_hyphen_diff], new_hyphen_rank = _ref1[0], new_hyphen_file = _ref1[1];
        tgt = g.generate_hyphen_position_bang_(new_hyphen_rank, new_hyphen_file);
        if (position_question_(tgt) && available_question_(tgt)) {
          potential_hyphen_moves.push(tgt);
        }
      }
      return potential_hyphen_moves;
    };
    getBasicPotentialMoves = function(chart2, chessman_hyphen_type) {
      var available_question_, board, file, offsets, rank, src, _ref;
      v.vow_hyphen_chart2(chart2);
      v.vow_hyphen_chessman_hyphen_type(chessman_hyphen_type);
      board = x.board_hyphen_from(chart2);
      src = x.position_hyphen_from(chart2);
      _ref = x.rank_hyphen__ampersand__hyphen_file_hyphen_from(src), rank = _ref[0], file = _ref[1];
      offsets = u.offsets_hyphen_for(chessman_hyphen_type);
      available_question_ = u.available_question_(board, src);
      return get_hyphen_basic_hyphen_potential_hyphen_moves(x.rank_hyphen_of(src), x.file_hyphen_of(src), u.offsets_hyphen_for(chessman_hyphen_type), u.available_question_(board, src));
    };
    getBasicPotentialMoves2 = function(bd, src, rts, passant, type) {
      var available_question_, dir, file, file_hyphen_diff, gen_hyphen_pos_bang_, inessent_question_, moves, new_hyphen_file, new_hyphen_rank, offsets, rank, rank_hyphen__ampersand__hyphen_file_hyphen_from, rank_hyphen_diff, tgt, _i, _len, _ref, _ref1;
      v.vow_hyphen_board(bd);
      v.vow_hyphen_position(src);
      v.vow_hyphen_chessman_hyphen_type(type);
      moves = [];
      rank_hyphen__ampersand__hyphen_file_hyphen_from = x.rank_hyphen__ampersand__hyphen_file_hyphen_from;
      _ref = rank_hyphen__ampersand__hyphen_file_hyphen_from(src), rank = _ref[0], file = _ref[1];
      offsets = u.offsets_hyphen_for(type);
      inessent_question_ = u.inessent_question_;
      gen_hyphen_pos_bang_ = g.generate_hyphen_position_bang_;
      available_question_ = u.available_question_(bd, src);
      for (_i = 0, _len = offsets.length; _i < _len; _i++) {
        dir = offsets[_i];
        _ref1 = rank_hyphen__ampersand__hyphen_file_hyphen_from(dir), rank_hyphen_diff = _ref1[0], file_hyphen_diff = _ref1[1];
        new_hyphen_rank = rank + rank_hyphen_diff;
        new_hyphen_file = file + file_hyphen_diff;
        tgt = gen_hyphen_pos_bang_(new_hyphen_rank, new_hyphen_file);
        if (inessent_question_(tgt) && available_question_(tgt)) {
          moves.push(tgt);
        }
      }
      return moves;
    };
    public_hyphen_fns = _.defaults([piece_hyphen_fns])({
      get_hyphen_basic_hyphen_potential_hyphen_moves: get_hyphen_basic_hyphen_potential_hyphen_moves,
      getBasicPotentialMoves: getBasicPotentialMoves,
      getBasicPotentialMoves2: getBasicPotentialMoves2
    });
    return public_hyphen_fns;
  });

}).call(this);
